version: '3'

services:
  db:
    image: mariadb:10
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin    
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      PMA_HOST: db
    networks:
      - wp-network

  wordpress:
    depends_on: 
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes: ['./wordpress:/var/www/html']
    networks:
      - wp-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-logs:/var/log/nginx
    networks:
      - wp-network

volumes:
  wordpress:
  dbdata:
  nginx-logs:

networks:
  wp-network:
    driver: bridge  
